[package]
name = "vnikey-ibus"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vnikey-ibus"
path = "src/main.rs"

[dependencies]
zbus = "4.4"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync"] }
vnikey-core = { path = "../vnikey-core" }
vnikey-config = { path = "../vnikey-config" }
